### ISSUE TITLE
Does this Bundle supports SF3

### ISSUE THREAD

**Issue by HVSoftware** [saadtazi/SaadTaziGChartBundle#14]
I see it is a nice Bundle. 

Does it support Symfony 3?

At least I will check this - using the demo page. An I will commit any modifications when needed. ;-)

**Comment by saadtazi** [comment]
I didn't try it myself, sorry :( but I'd be more than happy if you submit a PR for it!

Thanks in advance

**Comment by HVSoftware** [comment]
First results looks fine. I will summit a PR.

Change composer.json

    "require": {	
        "symfony/framework-bundle": "3.*"
 	},

app/autoload.php

    # https://github.com/saadtazi/SaadTaziGChartBundle
   $loader->add('SaadTazi', __DIR__.'/../vendor/bundles');

Routing

    Change pattern to path

It looks promising. The pages demo and demo2 are working. demo 3 shows a var_dump.

**Comment by GCalmels** [comment]
Hi,
Where are you with the PR? 
Need help?

**Comment by saadtazi** [comment]
Thank to @GCalmels , we now have `v2.0.0` that supports Symfony 3. Closing
