### ISSUE TITLE
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

### ISSUE THREAD

**Issue by Jingxuan31** [saadtazi/SaadTaziGChartBundle#16]
Hi Michael 
    I am testing my robot on TAZI and Arduino for ERSP right now. My code complies but not uploaded correctly.
The error is 
:avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
The first day when I got this error, I just plug USB out and put in agin to fix it.
But now I got the same error but I am not able to fix it.
My task is pretty easy--just drawing a happy face.

Best
Julia

**Comment by saadtazi** [comment]
?? Did you create an issue in the wrong github repo?

**Comment by Jingxuan31** [comment]
Oh! Sorry for that. I mean to report it in TAZI repo

**Comment by saadtazi** [comment]
No worry. Closing...
