### ISSUE TITLE
Routing error: Class does not exists

### ISSUE THREAD

**Issue by prakashsinghgaur** [saadtazi/SaadTaziGChartBundle#17]
I am using annotations in my project and this my controller code:-
`<?php
namespace SaadTazi\GChartBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use SaadTazi\GChartBundle\DataTable;
use SaadTazi\GChartBundle\Chart\PieChart;

class MychartController extends Controller
{
   
    public function showAction() {

        $dataTable2 = new DataTable\DataTable();
        $dataTable2->addColumn('id1', 'label 1', 'string');
        $dataTable2->addColumnObject(new DataTable\DataColumn('id2', 'label 2', 'number'));
        $dataTable2->addColumnObject(new DataTable\DataColumn('id3', 'label 3', 'number'));
        
        //test cells as array
        $dataTable2->addRow(array(
            array('v' => 'row 1'),
            array('v' => 2, 'f' => '2 trucks'),
            array('v' => 4, 'f' => '4 bikes')
        ));
        //simple cell (not an array)
        $dataTable2->addRow(array('row 2', 5, 1));
        //mixed
        $dataTable2->addRow(array('row 3', array('v' => 5), 10));
        $dataTable2->addRow(array('row 4', array('v' => 2), 0));
        $dataTable2->addRow(array('row 5', array('v' => 0), 10));
        $dataTable2->addRow(array('row 5', 10, 0));
        $dataTable2->addRow(array('row 5', 4, 5));

        return $this->render(
                    'SaadTaziGChartBundle:Demo:demo.html.twig', 
                    array('dataTable2' => $dataTable2->toArray());
    }
}`

Now if I visit any page of the site it throws error 

> Class SaadTazi\GChartBundle\Controller\MychartController does not exist in D:\xampp\htdocs\pmatsoftware\src\AppBundle/Controller/ (which is being imported from "D:\xampp\htdocs\pmatsoftware\app/config/routing.yml").

Can you explain how to manage/import routing for this bundle

**Comment by saadtazi** [comment]
Hi @prakashsinghgaur,

Did you register `Saadtazi` in `app/autoload.php` as stated in the README?

Disclaimer: It's been a long time I didn't use Symfony, so I am not sure if what I am suggesting is still "the way to do it".

**Comment by saadtazi** [comment]
inactive issue... closing .
