### ISSUE TITLE
Invalid service "twig.extension.g_chart"

### ISSUE THREAD

**Issue by Mohammadtrabelsi** [saadtazi/SaadTaziGChartBundle#19]
I use symfony 3.4.2 and SaadTazi\GChartBundle 2.0 
and i got this error:

> Invalid service "twig.extension.g_chart": the value of argument "twig.form.resources" of method "SaadTazi\GChartBundle\Twig\GChartExtension::__construct()" must be null, an instance of Symfony\Component\DependencyInjection\Reference or an instance of Symfony\Component\DependencyInjection\Definition, array given.

Any solution please:

this [link](https://stackoverflow.com/questions/46134150/fixing-twig-forms-resource-deprecation-in-symfony-3-3) my help

**Comment by saadtazi** [comment]
Hi @Mohammadtrabelsi , let me know if version [v3.0.0](https://packagist.org/packages/saad-tazi/g-chart-bundle#v3.0.0) fixes the issue.

Disclaimer:  Thank to @Xen3r0 (👏 👏 👏 ) who opened a PR, this issue should be fixed. I didn't get a chance to test this version myself, so please keep me posted 😉 ...and feel free to close this issue if it is fixed.

**Comment by saadtazi** [comment]
Closed by #18

**Comment by cbeyer** [comment]
Can you re-open ? I'm using version 3.1.1 with Symfony 4.4 and I've got the same error.

I have add this line in my configuration :
`twig.extension.visualization.template: '@SaadTaziGChart/chart/visualizationChart.html.twig'`

==> error `The service "twig.extension.g_chart" has a dependency on a non-existent service "SaadTaziGChart/chart/visualizationChart.html.twig".`

**Comment by saadtazi** [comment]
Sure @cbeyer . I won’t have time to see what’s going on. Feel free to open a PR if tou find a fix

**Comment by saadtazi** [comment]
@cbeyer : what twig version are you using? Did tou try v4 of this bundle?

**Comment by cbeyer** [comment]
I'm using twig/twig "v2.13.1"

V4 requires "symfony/framework-bundle: 5.*" :(

**Comment by saadtazi** [comment]
In order to test if it works, maybe you can install it [using a local path](https://getcomposer.org/doc/05-repositories.md#path), after cloning the repo and changing the [symfony version requirement](https://github.com/saadtazi/SaadTaziGChartBundle/blob/master/composer.json#L12)?

**Comment by amorebietakoUdala** [comment]
I have forked the SF4.X branch and make it work in SF 4.4. They are minor changes. I have made a minimum test and it seems to work.

@saadtazi do you have the pull request with the changes?

**Comment by saadtazi** [comment]
Thank you so much @amorebietakoUdala ! I just released v3.2.1.

@cbeyer : can you check if this new version works for you?

**Comment by cbeyer** [comment]
It works. Thanks ! 🥇

**Comment by amorebietakoUdala** [comment]
Glad to hear that.
