### ISSUE TITLE
Axis title in histogram

### ISSUE THREAD

**Issue by JoannaSM** [saadtazi/SaadTaziGChartBundle#24]
I dont understand. How can I add axis description in gchart_olumn_chart?

**Comment by saadtazi** [comment]
Hello,
This is how the datatable 2 is constructed for the first histogram in the [demo](https://github.com/saadtazi/SaadTaziGChartBundle/blob/master/Resources/views/Demo/demo.html.twig#L33) page:

https://github.com/saadtazi/SaadTaziGChartBundle/blob/master/Controller/DemoController.php#L63

You can also check datatable 8 in the Demo controller file (used for the second one).

I hope this helps.

**Comment by saadtazi** [comment]
Closing... Feel free to reopen/comment if you need further assistance.
